//
//  ListRepositoriesModels.swift
//  TopJavaRepositories
//
//  Created by Mauro Sasso Coletes on 14/09/19.
//  Copyright (c) 2019 MSC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListRepositories {

    struct Request {
        var page: Int
    }
    struct Response {
        var repositories: Repositories
    }
    
    struct ViewModel {
        var name: String
        var stars: Int
        var ownerName: String
        var ownerPhotoURL: URL
        var forks: Int
        var description: String
    }
    
    enum errors {
        case noInternet
        case tryAgain
    }

}
