//
//  ListRepositoriesRouter.swift
//  TopJavaRepositories
//
//  Created by Mauro Sasso Coletes on 14/09/19.
//  Copyright (c) 2019 MSC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListRepositoriesRoutingLogic {
    func routeToRepoPullRequests()
}

protocol ListRepositoriesDataPassing {
    var dataStore: ListRepositoriesDataStore? { get }
}

class ListRepositoriesRouter: ListRepositoriesRoutingLogic, ListRepositoriesDataPassing {
    
    weak var viewController: ListRepositoriesViewController?
    var dataStore: ListRepositoriesDataStore?

    func routeToRepoPullRequests() {
        let vc = PullRequestRepoViewController()
        var destinationDS = vc.router!.dataStore!
        passDataToPullRequest(source: dataStore!, destination: &destinationDS)
        self.viewController?.navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
        viewController?.navigationController?.pushViewController(vc, animated: true)
    }
    
    private func passDataToPullRequest(source: ListRepositoriesDataStore, destination: inout PullRequestRepoDataStore) {
        destination.owner = source.owner
        destination.name = source.name
    }
}
