//
//  PullRequestRepoPresenter.swift
//  TopJavaRepositories
//
//  Created by Mauro Sasso Coletes on 14/09/19.
//  Copyright (c) 2019 MSC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
// This tag below is used to create the testable files from the Cuckoo pod
// CUCKOO_TESTABLE

import UIKit

protocol PullRequestRepoPresentationLogic {
    func displayError(type: ListRepositories.errors, tryAgainAction: EmptyClosure?)
    func reloadTable()
    func presentLoading()
    func hideLoading()
    func presentViewModelFromModel(pullRequest: PullRequest) -> PullRequestRepo.ViewModel?
    func presentTitle(title: String)
}

class PullRequestRepoPresenter: PullRequestRepoPresentationLogic {
    
    weak var viewController: PullRequestRepoDisplayLogic?

    func displayError(type: ListRepositories.errors, tryAgainAction: EmptyClosure?) {
        switch type {
        case .noInternet:
            viewController?.displayError(message: R.string.topRatedJavaRepositories.noInternetConnectionMessage(), actionButtonTitle: nil, tryAgainAction: nil)
        default:
            viewController?.displayError(message: R.string.topRatedJavaRepositories.tryAgainMessage(), actionButtonTitle: R.string.topRatedJavaRepositories.tryAgainActionTitle(), tryAgainAction: tryAgainAction)
        }
    }
    func reloadTable() {
        viewController?.reloadTable()
    }
    
    func presentViewModelFromModel(pullRequest: PullRequest) -> PullRequestRepo.ViewModel? {
        guard let url = URL(string: pullRequest.user.avatarURL) else {
            return nil
        }
        return PullRequestRepo.ViewModel(title: pullRequest.title, body: pullRequest.body, ownerName: pullRequest.user.login, ownerPhotoURL: url)
    }
    
    func presentLoading() {
        viewController?.showLoading()
    }
    
    func hideLoading() {
        viewController?.hideLoading()
    }
    
    func presentTitle(title: String) {
        viewController?.showTitle(title: title)
    }

}
