//
//  PullRequestRepoModels.swift
//  TopJavaRepositories
//
//  Created by Mauro Sasso Coletes on 14/09/19.
//  Copyright (c) 2019 MSC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PullRequestRepo {

    struct Request {
        var owner: String
        var name: String
    }
    struct Response {
        var pullRequests: [PullRequest]
    }
    struct ViewModel {
        var title: String
        var body: String
        var ownerName: String
        var ownerPhotoURL: URL
    }

}
