//
//  PullRequestRepoViewController.swift
//  TopJavaRepositories
//
//  Created by Mauro Sasso Coletes on 14/09/19.
//  Copyright (c) 2019 MSC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PullRequestRepoDisplayLogic: class, ViewControllerBaseProtocol {
    func reloadTable()
    func showLoading()
    func hideLoading()
    func showTitle(title: String)
}

class PullRequestRepoViewController: UIViewController {

    var interactor: PullRequestRepoBusinessLogic?
    var router: (PullRequestRepoRoutingLogic & PullRequestRepoDataPassing)?

    @IBOutlet weak var tableView: UITableView!
    
    init() {
        super.init(nibName: "PullRequestRepoViewController", bundle: Bundle.main)
        setup()
    }

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    private func setup() {
        let viewController = self
        let interactor = PullRequestRepoInteractor()
        let presenter = PullRequestRepoPresenter()
        let router = PullRequestRepoRouter()
        viewController.interactor = interactor
        viewController.router = router
        presenter.viewController = viewController
        interactor.presenter = presenter
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interactor?.getTitle()
        configureTableView()
        interactor?.getPullrequests()
    }
    
    private func configureTableView() {
        tableView.dataSource = self
        tableView.delegate = self
        tableView.estimatedRowHeight = 60
        tableView.rowHeight = UITableView.automaticDimension
    }
}

extension PullRequestRepoViewController: UITableViewDataSource, UITableViewDelegate {
    
    func PullRequestRepoViewController(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return interactor?.numbeOfRows() ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell: PullRequestRepoCell = tableView.dequeueReusableCell(for: indexPath)
        if let item = interactor?.viewModelForIndex(index: indexPath.row) {
            cell.configure(name: item.title, pullDescription: item.body, repoImage: item.ownerPhotoURL, username: item.ownerName)
            return cell
        }
        return UITableViewCell()
    }
}

extension PullRequestRepoViewController: PullRequestRepoDisplayLogic {
    func reloadTable() {
        DispatchQueue.main.async {
            self.tableView.reloadData()
        }
    }
    
    func showLoading() {
        DispatchQueue.main.async {
            self.tableView.addSpinnerToFooterView()
        }
    }
    func hideLoading() {
        DispatchQueue.main.async {
            self.tableView.tableFooterView = nil
        }
    }
    func showTitle(title: String) {
        self.title = title
    }
}
